#! /bin/zsh
SRC="./src/";
BIN="./bin/";

g++ -std=c++20 -c $SRC"HPLabrynth.cpp" -o $BIN".HPLabrynth.o"
g++ -std=c++20 -c $SRC"HPLabMain.cpp" -o $BIN".main.o"
g++ -std=c++20 $BIN".main.o" $BIN".HPLabrynth.o" -o $BIN"HPLabrynth"

