#! /bin/zsh
SRC="./src/";
BIN="./bin/";
mkdir $BIN
g++ -std=c++20 -O3 -c $SRC"HPLabrynth.cpp" -o $BIN".HPLabrynth.o"
g++ -std=c++20 -O3 -c $SRC"HPLabMain.cpp" -o $BIN".main.o"
g++ -std=c++20 -O3 $BIN".main.o" $BIN".HPLabrynth.o" -o $BIN"HPLabrynthO3"

