#! /bin/zsh
mkdir -p ./files/auto/

for i in {5..25}; do
    ./bin/HPLabrynth --rand="$i $i 1 1 $i $i" --out="files/auto/lab$i.txt"
    ./bin/HPLabrynth --rand="$i $i 1 1 $i $i" --skip > "files/auto/lab_unchecked$i.txt"
done
